export enum NotificationType {
  AGENT_LEFT_COMPANY = 'AGENT_LEFT_COMPANY',
  AGENT_JOINED_COMPANY = 'AGENT_JOINED_COMPANY',
  AGENT_INCIDENT_REPORTED = 'AGENT_INCIDENT_REPORTED',
  PARCEL_REASSIGNED = 'PARCEL_REASSIGNED',
  PARCEL_NEEDS_MANUAL_ASSIGNMENT = 'PARCEL_NEEDS_MANUAL_ASSIGNMENT',
}
